theme: jekyll-theme-midnight
title: Battle Wizards Arena
description: First person arena style game, which allows the player to enter a procedurally generated and editable arena, and use spells to combat against other wizards. 
